"""add boarding table

Revision ID: 35cf7f04a3d3
Revises: fb7a2f1649f6
Create Date: 2026-07-16 02:35:45.675366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cf7f04a3d3'
down_revision: Union[str, Sequence[str], None] = 'fb7a2f1649f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('boarding_time', sa.DateTime(), nullable=False),
    sa.Column('gate', sa.String(length=20), nullable=False),
    sa.Column('boarding_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_boardings_id'), 'boardings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boardings_id'), table_name='boardings')
    op.drop_table('boardings')
    # ### end Alembic commands ###
