"""update seat model

Revision ID: 36e3705d6896
Revises: eef90152a4b5
Create Date: 2026-07-16 16:16:45.261133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e3705d6896'
down_revision: Union[str, Sequence[str], None] = 'eef90152a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'seats', ['seat_id'], ['id'])
    op.add_column(
    'seats',
    sa.Column(
        'row',
        sa.Integer(),
        nullable=True
        )
    )

    op.add_column(
        'seats',
        sa.Column(
            'seat_letter',
            sa.String(length=1),
            nullable=True
        )
    )
    op.add_column('seats', sa.Column('is_window', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('is_aisle', sa.Boolean(), nullable=True))
    op.add_column('seats', sa.Column('is_emergency_exit', sa.Boolean(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seats', 'availability',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('seats', 'seat_class',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('seats', 'seat_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('seats', 'flight_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('seats', 'is_emergency_exit')
    op.drop_column('seats', 'is_aisle')
    op.drop_column('seats', 'is_window')
    op.drop_column('seats', 'seat_letter')
    op.drop_column('seats', 'row')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'seat_id')
    # ### end Alembic commands ###
