"""complete_models

Revision ID: d4f451c08c65
Revises: d90f2085bb7f
Create Date: 2026-07-15 02:46:49.151049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f451c08c65'
down_revision: Union[str, Sequence[str], None] = 'd90f2085bb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_crew_id'), 'crew', ['id'], unique=False)
    op.create_table('runways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runway_number', sa.String(length=20), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runway_number')
    )
    op.create_table('terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terminal_name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_name')
    )
    op.create_index(op.f('ix_terminals_id'), 'terminals', ['id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_aircraft_id'), 'aircraft', ['id'], unique=False)
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_number', sa.String(length=20), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_number')
    )
    op.create_index(op.f('ix_gates_id'), 'gates', ['id'], unique=False)
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('travel_class', sa.String(length=30), nullable=True),
    sa.Column('ticket_price', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.Column('booking_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('crew_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crew.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_assignments_id'), 'crew_assignments', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('seat_class', sa.String(length=30), nullable=True),
    sa.Column('availability', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('baggage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baggage_tag', sa.String(length=50), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baggage_tag')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('flights', sa.Column('airline_id', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('flights', sa.Column('destination', sa.String(length=100), nullable=False))
    op.add_column('flights', sa.Column('departure_time', sa.DateTime(), nullable=False))
    op.add_column('flights', sa.Column('arrival_time', sa.DateTime(), nullable=False))
    op.add_column('flights', sa.Column('terminal', sa.String(length=20), nullable=False))
    op.add_column('flights', sa.Column('gate_id', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('aircraft_id', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'flights', 'gates', ['gate_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'airlines', ['airline_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'aircraft', ['aircraft_id'], ['id'])
    op.drop_column('flights', 'arrival')
    op.drop_column('flights', 'departure')
    op.add_column('passengers', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('passengers', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('passengers', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('passengers', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('passengers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('passengers', 'passport_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_unique_constraint(None, 'passengers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passengers', type_='unique')
    op.alter_column('passengers', 'passport_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('passengers', 'created_at')
    op.drop_column('passengers', 'gender')
    op.drop_column('passengers', 'email')
    op.drop_column('passengers', 'last_name')
    op.drop_column('passengers', 'first_name')
    op.add_column('flights', sa.Column('departure', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('arrival', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'created_at')
    op.drop_column('flights', 'aircraft_id')
    op.drop_column('flights', 'gate_id')
    op.drop_column('flights', 'terminal')
    op.drop_column('flights', 'arrival_time')
    op.drop_column('flights', 'departure_time')
    op.drop_column('flights', 'destination')
    op.drop_column('flights', 'source')
    op.drop_column('flights', 'airline_id')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('baggage')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_crew_assignments_id'), table_name='crew_assignments')
    op.drop_table('crew_assignments')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_maintenance_id'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('ix_gates_id'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_aircraft_id'), table_name='aircraft')
    op.drop_table('aircraft')
    op.drop_table('weather')
    op.drop_index(op.f('ix_terminals_id'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_table('runways')
    op.drop_index(op.f('ix_crew_id'), table_name='crew')
    op.drop_table('crew')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
