"""add baggage module

Revision ID: eef90152a4b5
Revises: 35cf7f04a3d3
Create Date: 2026-07-16 11:12:48.691989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef90152a4b5'
down_revision: Union[str, Sequence[str], None] = '35cf7f04a3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baggage', sa.Column('current_location', sa.String(length=100), nullable=True))
    op.add_column('baggage', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('baggage', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('baggage', 'weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.create_index(op.f('ix_baggage_id'), 'baggage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baggage_id'), table_name='baggage')
    op.alter_column('baggage', 'weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('baggage', 'booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('baggage', 'created_at')
    op.drop_column('baggage', 'current_location')
    # ### end Alembic commands ###
